apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    project: roboshop
    environment: production
    compenent: frontend
    version: v1
spec:
  containers:
  - name: frontend
    image: nginx