apiVersion: v1
kind: Pod
metadata:
  name: resource-limits-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "68Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "120m"