apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: ENVIRONMENT
      value: production
    - name: LOG_LEVEL
      value: debug